#!/usr/bin/env python3
"""Generate the ucore RTL table artifacts from the in-repo dumps.

    python3 sw/gen_ucore_tables.py [--check]

Emits (into hdl/rtl/ucore/):
  ucrom.hex          1028 x 29b   microcode rows, addressed by {bank[8:0], row[1:0]}
  ucdecode.hex       8192 x 10b   {valid, bank[8:0]}, addressed by the 13-bit
                                  micro-address {page[2:0], opc[7:0], rowgrp[1:0]}
  pla3_tables.svh    3 x 256 x 14b combinational case ROM + named accessors
  ucrom_census.json  the provenance census (counts, the ambiguous address,
                     resource arithmetic, source digests)

Sources: docs/V20BITS.TXT (normative spec docs/V20UCDIS.PAS::ReadBits) and
docs/pla3_outputs.txt.  The parse is a transliteration of sim/ucrom.cpp; see
sw/ucore_tables.py.  Gate G0 (`sw/check_ucore_tables.py`) proves the emitted
artifacts byte-match the SIM's own tables for all 1028 rows, all 8192
micro-addresses and all 768 PLA entries.

--check re-generates into memory and fails if any on-disk artifact differs
(the "generated files are stale" guard).
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ucore_tables import (  # noqa: E402
    ADDR_COUNT, OPC_COUNT, PLA3, ROOT, ROW_COUNT, UPC_COUNT, V20BITS,
    UcRom, load_pla3)

OUT = ROOT / "hdl/rtl/ucore"

BANNER = ("// GENERATED by sw/gen_ucore_tables.py from docs/V20BITS.TXT and\n"
          "// docs/pla3_outputs.txt.  DO NOT HAND-EDIT.  Gate G0\n"
          "// (`python3 sw/check_ucore_tables.py`) proves this file byte-matches\n"
          "// the C++ reference model's own tables.\n")

# --- PLA3 named columns, semantics verbatim from sim/pla3_table.h ------------
PLA_COLS = [
    ("BYTE_ONLY",     13, "b0  byte-width-only data op, no W bit"),
    ("W_FROM_BIT0",   12, "b1  operand width = opcode bit 0"),
    ("ONE_BYTE_LOGIC", 11, "b2  1BL: executed by logic, no microcode"),
    ("ACC_W_OPERAND", 10, "b3  implicit AL/AW operand, width from W"),
    ("SREG_MOV",       9, "b4  MOV to/from a segment register (8C/8E)"),
    ("HAS_MODRM",      8, "b5  a ModR/M byte follows"),
    ("MODRM_STORE",    7, "b6  r/m operand written without being read"),
    ("DIR_FROM_BIT1",  6, "b7  source/destination direction = opcode bit 1"),
    ("NATIVE_HI",      5, "b8  native opcode >= 0x80 (map-half select)"),
    ("INCDEC_NO_CY",   4, "b9  INC/DEC class: CY must not be updated"),
]


def build_rom_hex(rom):
    # Pure data, no comments: $readmemh word lists are also read by Quartus,
    # whose 17.1 lexer is not worth betting a synthesis run on.  Provenance
    # lives in ucrom_census.json and hdl/rtl/ucore/README.md.
    return "".join("%08X\n" % rom.ops[i].word29 for i in range(ROW_COUNT))


def build_decode_hex(rom):
    out = []
    for addr in range(ADDR_COUNT):
        b = rom.bank_of(addr, emu=False)
        out.append("%03X\n" % (0 if b < 0 else (0x200 | b)))
    return "".join(out)


def build_pla_svh(pla):
    L = [BANNER.rstrip("\n"),
         "//",
         "// The group-decode PLA: a 2-bit decode-mode prefix + the 8 opcode",
         "// bits -> a 14-bit vector.  Three separate 256-entry tables",
         "// (sim/pla3_table.h):",
         "//     prefix 01 -> native   (native V20/V30 first-byte opcode)",
         "//     prefix 00 -> mode8080 (8080 emulation mode, entered by BRKEM)",
         "//     prefix 11 -> ext      (second byte of the 0F extension page)",
         "//",
         "// Bit numbering matches the model: the dumps print the vector",
         "// MSB-first as b0..b13 and b0 is stored in bit 13, so XOP[3:0]",
         "// (b10..b13) lands in the low nibble.",
         "//",
         "// `include this inside a module body.  Pure combinational case ROMs;",
         "// no state, no clock.",
         "",
         "  // --- decode-mode prefixes ---",
         "  localparam logic [1:0] PLA3_MODE_8080 = 2'b00;",
         "  localparam logic [1:0] PLA3_MODE_NATIVE = 2'b01;",
         "  localparam logic [1:0] PLA3_MODE_EXT    = 2'b11;",
         "",
         "  // --- named columns (sim/pla3_table.h::Col) ---"]
    for name, bit, doc in PLA_COLS:
        L.append("  localparam logic [13:0] PLA3_%-15s = 14'h%04X; // %s"
                 % (name, 1 << bit, doc))
    L += [
        "  // b10..b13 = XOP[3:0], a 4-bit auxiliary op-select field.",
        "  localparam logic [13:0] PLA3_XOP_MASK      = 14'h000F;",
        "",
        "  // --- XOP[3:0] when ONE_BYTE_LOGIC is set (sim/pla3_table.h::Bl1Op) ---",
        "  localparam logic [3:0] PLA3_BL1_SEG_PREFIX = 4'h0; // 26/2E/36/3E",
        "  localparam logic [3:0] PLA3_BL1_EXT_PREFIX = 4'h1; // native 0F, 8080 ED",
        "  localparam logic [3:0] PLA3_BL1_SET_DIR    = 4'h2; // STD",
        "  localparam logic [3:0] PLA3_BL1_CLR_DIR    = 4'h3; // CLD",
        "  localparam logic [3:0] PLA3_BL1_SET_IE     = 4'h4; // EI (STI)",
        "  localparam logic [3:0] PLA3_BL1_CLR_IE     = 4'h5; // DI (CLI)",
        "  localparam logic [3:0] PLA3_BL1_SET_CY     = 4'h6; // STC",
        "  localparam logic [3:0] PLA3_BL1_CLR_CY     = 4'h7; // CLC",
        "  localparam logic [3:0] PLA3_BL1_REPC_PFX   = 4'h8; // REPC",
        "  localparam logic [3:0] PLA3_BL1_REPNC_PFX  = 4'h9; // REPNC",
        "  localparam logic [3:0] PLA3_BL1_NOT_CY     = 4'hA; // CMC",
        "  localparam logic [3:0] PLA3_BL1_HALT       = 4'hB; // HALT",
        "  localparam logic [3:0] PLA3_BL1_REP_PFX    = 4'hC; // REP/REPE",
        "  localparam logic [3:0] PLA3_BL1_REPNE_PFX  = 4'hD; // REPNE",
        "  localparam logic [3:0] PLA3_BL1_LOCK_ALIAS = 4'hE; // undocumented F1",
        "  localparam logic [3:0] PLA3_BL1_LOCK       = 4'hF; // BUSLOCK",
        "",
        "  // --- named accessors (sim/pla3_table.h constexpr predicates) ---"]
    for name, bit, _doc in PLA_COLS:
        fn = "pla3_" + name.lower()
        L += ["  function automatic logic %s(input logic [13:0] pla_v);" % fn,
              "    %s = pla_v[%d];" % (fn, bit),
              "  endfunction"]
    L += [
        "  function automatic logic [3:0] pla3_xop(input logic [13:0] pla_v);",
        "    pla3_xop = pla_v[3:0];",
        "  endfunction",
        "",
        "  // sim/pla3_table.h::is_prefix -- consume the byte and re-decode.",
        "  function automatic logic pla3_is_prefix(input logic [13:0] pla_v);",
        "    logic p;",
        "    p = 1'b0;",
        "    if (pla_v[11]) begin",
        "      case (pla_v[3:0])",
        "        PLA3_BL1_SEG_PREFIX, PLA3_BL1_EXT_PREFIX,",
        "        PLA3_BL1_REPC_PFX,   PLA3_BL1_REPNC_PFX,",
        "        PLA3_BL1_REP_PFX,    PLA3_BL1_REPNE_PFX,",
        "        PLA3_BL1_LOCK_ALIAS, PLA3_BL1_LOCK: p = 1'b1;",
        "        default: p = 1'b0;",
        "      endcase",
        "    end",
        "    pla3_is_prefix = p;",
        "  endfunction",
        ""]

    for name, table in (("native", pla["native"]),
                        ("mode8080", pla["mode8080"]),
                        ("ext", pla["ext"])):
        L += ["  // --- prefix %s: %s ---" % (
                  {"native": "01", "mode8080": "00", "ext": "11"}[name], name),
              "  function automatic logic [13:0] pla3_%s(input logic [7:0] pla_op);"
              % name,
              "    case (pla_op)"]
        for i in range(256):
            L.append("      8'h%02X: pla3_%s = 14'h%04X;" % (i, name, table[i]))
        L += ["      default: pla3_%s = 14'h0000;" % name,
              "    endcase",
              "  endfunction",
              ""]

    L += ["  // Mode-selected lookup.  Prefix 10 is unused by the part and",
          "  // returns the all-zero vector.",
          "  function automatic logic [13:0] pla3_lookup(input logic [1:0] pla_mode,",
          "                                              input logic [7:0] pla_op);",
          "    case (pla_mode)",
          "      PLA3_MODE_NATIVE: pla3_lookup = pla3_native(pla_op);",
          "      PLA3_MODE_8080:   pla3_lookup = pla3_mode8080(pla_op);",
          "      PLA3_MODE_EXT:    pla3_lookup = pla3_ext(pla_op);",
          "      default:          pla3_lookup = 14'h0000;",
          "    endcase",
          "  endfunction",
          ""]
    return "\n".join(L) + "\n"


def build_census(rom, pla, arts):
    mapped = ADDR_COUNT - rom.unmapped
    amb = []
    for a in rom.ambiguous:
        amb.append({
            "addr": "0x%04X" % a,
            "pattern": "%s.%s.%s" % (format((a >> 10) & 7, "03b"),
                                     format((a >> 2) & 0xFF, "08b"),
                                     format(a & 3, "02b")),
            "page": (a >> 10) & 7,
            "opcode": "0x%02X" % ((a >> 2) & 0xFF),
            "rowgrp": a & 3,
            "bank_first_match": rom.bank_first[a],
            "bank_second_match": rom.bank_alt[a],
            "resolved_native": rom.bank_of(a, emu=False),
            "resolved_emu": rom.bank_of(a, emu=True),
            "rows_native": ["0x%04X" % (rom.bank_of(a) * 4 + r)
                            for r in range(4)],
            "rows_emu": ["0x%04X" % (rom.bank_of(a, True) * 4 + r)
                         for r in range(4)],
            "note": ("the interrupt-acknowledge vector fetch (ucsim ledger R4). "
                     "Exactly two activation patterns match and the 13 dumped "
                     "address bits cannot separate them, so the real decoder "
                     "takes a 14th input (8080-emulation mode). The generated "
                     "ucdecode.hex is the NATIVE resolution = the SECOND "
                     "matching pattern, byte-identical to "
                     "sim/ucrom.h::bank_of(emu=false). The emulation-mode "
                     "alternative is recorded here, NOT emitted: ucore has no "
                     "BRKEM path at U0 and a second table would be dead "
                     "silicon."),
        })

    # rowgrp dependence: how much of the decode is actually 15-bit
    rowgrp_varies = 0
    pageopc_mapped = 0
    for p in range(8):
        for o in range(256):
            banks = [rom.bank_of((p << 10) | (o << 2) | g) for g in range(4)]
            m = [b for b in banks if b >= 0]
            if m:
                pageopc_mapped += 1
            if len(set(m)) > 1:
                rowgrp_varies += 1

    return {
        "generator": "sw/gen_ucore_tables.py",
        "sources": {
            "docs/V20BITS.TXT": sha(V20BITS.read_bytes()),
            "docs/pla3_outputs.txt": sha(PLA3.read_bytes()),
        },
        "normative_spec": "docs/V20UCDIS.PAS (procedure ReadBits)",
        "transliterated_from": "sim/ucrom.cpp (UcRom::load, UcRom::build_decode)",
        "ucrom": {
            "banks": OPC_COUNT,
            "rows": ROW_COUNT,
            "row_width_bits": 29,
            "match_addr_space": ADDR_COUNT,
            "match_addr_mapped": mapped,
            "match_addr_unmapped": rom.unmapped,
            "ambiguous_count": len(rom.ambiguous),
            "ambiguous": amb,
            "upc_width_bits": 15,
            "upc_space": UPC_COUNT,
            "pageopc_with_any_mapping": pageopc_mapped,
            "pageopc_bank_varies_with_rowgrp": rowgrp_varies,
        },
        "pla3": {
            "tables": 3, "entries_per_table": 256, "width_bits": 14,
            "total_entries": 768,
            "nonzero": {k: sum(1 for v in t if v) for k, t in pla.items()},
            "distinct": {k: len(set(t)) for k, t in pla.items()},
        },
        "resource_arithmetic": {
            "note": ("M10K = 10240 bits. Split-table layout is what is emitted; "
                     "the single fully-flat alternative is recorded for the U1 "
                     "BRAM decision."),
            "ucdecode_bits": ADDR_COUNT * 10,
            "ucrom_bits": ROW_COUNT * 29,
            "split_total_bits": ADDR_COUNT * 10 + ROW_COUNT * 29,
            "split_m10k_min": round((ADDR_COUNT * 10 + ROW_COUNT * 29) / 10240, 2),
            "fully_flat_upc_bits": UPC_COUNT * 30,
            "fully_flat_m10k_min": round(UPC_COUNT * 30 / 10240, 2),
        },
        "artifacts": {name: sha(text.encode()) for name, text in arts.items()},
    }


def sha(b):
    return "sha256:" + hashlib.sha256(b).hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the on-disk artifacts differ from a fresh "
                         "generation (staleness guard)")
    args = ap.parse_args()

    rom = UcRom()
    pla = load_pla3()

    arts = {
        "ucrom.hex": build_rom_hex(rom),
        "ucdecode.hex": build_decode_hex(rom),
        "pla3_tables.svh": build_pla_svh(pla),
    }
    census = build_census(rom, pla, arts)
    arts["ucrom_census.json"] = json.dumps(census, indent=2) + "\n"

    if args.check:
        bad = []
        for name, text in arts.items():
            p = OUT / name
            if not p.exists():
                bad.append(f"{name}: MISSING")
            elif p.read_text() != text:
                bad.append(f"{name}: STALE (differs from a fresh generation)")
        if bad:
            print("gen_ucore_tables --check: FAIL")
            for b in bad:
                print("  -", b)
            return 1
        print(f"gen_ucore_tables --check: PASS ({len(arts)} artifacts current)")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in arts.items():
        (OUT / name).write_text(text)
        print(f"wrote {OUT / name}")
    print(f"\nucrom : {OPC_COUNT} banks / {ROW_COUNT} rows x 29b; "
          f"{ADDR_COUNT - rom.unmapped}/{ADDR_COUNT} micro-addresses mapped, "
          f"{len(rom.ambiguous)} ambiguous")
    print(f"pla3  : 3 x 256 x 14b")
    return 0


if __name__ == "__main__":
    sys.exit(main())
