// alu.cpp -- see alu.h.

#include "alu.h"

namespace sim {

namespace {

inline uint16_t parity8(uint16_t r) {
    uint8_t v = uint8_t(r & 0xFF);
    v ^= uint8_t(v >> 4);
    v ^= uint8_t(v >> 2);
    v ^= uint8_t(v >> 1);
    return (v & 1) ? 0 : kFlagP;  // even parity -> P = 1
}

inline uint16_t szp(uint32_t r, bool byte) {
    uint16_t f = 0;
    uint32_t mask = byte ? 0xFFu : 0xFFFFu;
    uint32_t msb = byte ? 0x80u : 0x8000u;
    if ((r & mask) == 0) f |= kFlagZ;
    if (r & msb) f |= kFlagS;
    f |= parity8(uint16_t(r));
    return f;
}

constexpr uint16_t kArithMask =
    kFlagCY | kFlagP | kFlagAC | kFlagZ | kFlagS | kFlagV;

// --- BCD adjust (ADJD/ADJA latched, executed by the following ADD/SUB) -----
// The adjust is one pass through the adder: `corr` is generated by the
// decimal-adjust logic and added to / subtracted from AL.
AluResult bcd_adjust(const Machine& m, uint8_t adjust, bool sub, uint16_t a) {
    AluResult res;
    uint32_t al = a & 0xFFu;
    bool cy_in = (m.psw & kFlagCY) != 0;
    bool ac_in = (m.psw & kFlagAC) != 0;
    bool lo_adj = ((al & 0x0Fu) > 9) || ac_in;
    bool hi_adj = false;
    uint32_t corr = lo_adj ? 6u : 0u;
    if (adjust == 1) {  // ADJD: decimal adjust (ADJ4A / ADJ4S)
        // MEASURED (fit, 2000/2000 on v0.2 27+2F): the high correction is a
        // NIBBLE comparison plus a decimal carry out of the low nibble --
        // and that carry is generated only by the "digit > 9" test, not by a
        // correction that AC forced.  (x86's `AL > 0x99` differs exactly on
        // AL = 9A..9F with AC=1, where the V30 does NOT correct the high
        // digit.)
        hi_adj = ((al >> 4) > 9) || cy_in ||
                 ((al >> 4) == 9 && (al & 0x0Fu) > 9 && !ac_in);
        if (hi_adj) corr += 0x60u;
    }
    uint32_t sum = sub ? (al - corr) : (al + corr);
    // ADJA truncates to one BCD digit; ADJD keeps the byte.  The FLAGS come
    // from the (untruncated) adder pass either way.
    res.value = uint16_t(adjust == 2 ? (sum & 0x0Fu) : (sum & 0xFFu));

    uint16_t f = szp(sum & 0xFFu, true);
    bool cy = (adjust == 2) ? lo_adj : hi_adj;
    if (cy) f |= kFlagCY;
    if (lo_adj) f |= kFlagAC;
    uint32_t bb = corr & 0xFFu;
    uint32_t rr = sum & 0xFFu;
    if (sub) {
        if (((al ^ bb) & (al ^ rr)) & 0x80u) f |= kFlagV;
    } else {
        if ((~(al ^ bb) & (al ^ rr)) & 0x80u) f |= kFlagV;
    }
    res.flags = f;
    res.flag_mask = kArithMask;
    return res;
}

}  // namespace

uint8_t alu_opc_select(const Machine& m) {
    uint8_t sel = m.opc_from_modrm ? uint8_t(m.modrm_reg & 7)
                                   : uint8_t((m.opc_reg >> 3) & 7);
    return uint8_t(m.opc_base + sel);
}

AluResult alu_eval(const Machine& m, const AluLatch& lat) {
    AluResult res;
    if (lat.ea_const) {
        res.value = lat.ea_value;
        res.flag_mask = 0;
        return res;
    }

    uint8_t op = lat.op;
    if (op == kOpc) op = alu_opc_select(m);

    // The datapath is 16 bits wide ALWAYS for the ADD-class ops; `byte`
    // selects only where the flag taps sit.  (Forced by the string blocks --
    // see the ledger, "ALU width".)  The iterative shift/multiply ops are the
    // exception: they are width-confined (their carry chain wraps at the
    // operand width) and are stepped by alu_step().
    bool byte = lat.byte && op != kInc2 && op != kDec2;
    const uint16_t tmps[4] = {m.tmpa, m.tmpb, m.tmpc, 0};
    uint32_t af = m.tmpb;                     // port A
    uint32_t bf = tmps[lat.tmp & 3];          // port B
    uint32_t mask = byte ? 0xFFu : 0xFFFFu;
    uint32_t msb = byte ? 0x80u : 0x8000u;
    uint32_t a = af & mask;
    uint32_t b = bf & mask;
    uint32_t rfull = 0;
    uint32_t r = 0;
    uint16_t f = 0;
    uint16_t fm = 0;
    uint32_t cin = (m.psw & kFlagCY) ? 1u : 0u;

    if (lat.adjust && (op == kAdd || op == kSub)) {
        AluResult br = bcd_adjust(m, lat.adjust, op == kSub, m.tmpb);
        // The result rides the 16-bit bus; only the low byte is meaningful.
        br.value = uint16_t((m.tmpb & 0xFF00u) | (br.value & 0xFFu));
        return br;
    }

    if (alu_is_iterative(op)) {
        // COUNT exhausted: the iterative unit passes port A straight through
        // (D0/D1 row 0117 and SHIFT row 022A both re-read SIGMA after the
        // loop and must see the shifted value, not another shift).
        res.value = m.tmpb;
        res.flag_mask = 0;
        return res;
    }

    switch (op) {
        case kAdd:
        case kAdc: {
            uint32_t c = (op == kAdc) ? cin : 0u;
            r = a + b + c;
            rfull = af + bf + c;
            fm = kArithMask;
            if (r & (mask + 1)) f |= kFlagCY;
            if ((a ^ b ^ r) & 0x10u) f |= kFlagAC;
            if ((~(a ^ b) & (a ^ r)) & msb) f |= kFlagV;
            f |= szp(r, byte);
            break;
        }
        case kSub:
        case kSbb:
        case kCmp: {
            uint32_t c = (op == kSbb) ? cin : 0u;
            r = a - b - c;
            rfull = af - bf - c;
            fm = kArithMask;
            if (r & (mask + 1)) f |= kFlagCY;
            if ((a ^ b ^ r) & 0x10u) f |= kFlagAC;
            if (((a ^ b) & (a ^ r)) & msb) f |= kFlagV;
            f |= szp(r, byte);
            if (op == kCmp) res.commits = false;
            break;
        }
        case kAnd:
        case kOr:
        case kXor: {
            r = (op == kAnd) ? (a & b) : (op == kOr) ? (a | b) : (a ^ b);
            rfull = (op == kAnd) ? (af & bf) : (op == kOr) ? (af | bf) : (af ^ bf);
            fm = kArithMask;
            // MEASURED (docs/facts/undefined_flags.md): AC always 0 for the
            // logic ops; CY and V always 0 (documented).
            f |= szp(r, byte);
            break;
        }
        case kInc: {
            r = b + 1u;
            rfull = bf + 1u;
            fm = kFlagP | kFlagAC | kFlagZ | kFlagS | kFlagV;  // CY preserved
            if ((b ^ 1u ^ r) & 0x10u) f |= kFlagAC;
            if ((~(b ^ 1u) & (b ^ r)) & msb) f |= kFlagV;
            f |= szp(r, byte);
            break;
        }
        case kDec: {
            r = b - 1u;
            rfull = bf - 1u;
            fm = kFlagP | kFlagAC | kFlagZ | kFlagS | kFlagV;  // CY preserved
            if ((b ^ 1u ^ r) & 0x10u) f |= kFlagAC;
            if (((b ^ 1u) & (b ^ r)) & msb) f |= kFlagV;
            f |= szp(r, byte);
            break;
        }
        case kInc2:
            r = b + 2u;
            rfull = bf + 2u;
            fm = 0;
            break;
        case kDec2:
            r = b - 2u;
            rfull = bf - 2u;
            fm = 0;
            break;
        case kNot:
            r = ~b;
            rfull = ~bf;
            fm = 0;  // V30 NOT touches no flags
            break;
        case kNeg:
            r = 0u - b;
            rfull = 0u - bf;
            fm = kArithMask;
            if ((r & mask) != 0) f |= kFlagCY;
            if ((b ^ r) & 0x10u) f |= kFlagAC;
            if (b == msb) f |= kFlagV;
            f |= szp(r, byte);
            break;
        case kAbs: {
            // [-1E-]: magnitude.  Used only to feed the signed MUL/DIV
            // routines; the sign it strips is recorded by the row that
            // LATCHES it (exec.cpp), not here.
            bool neg = (b & msb) != 0;
            r = neg ? ((0u - b) & mask) : b;
            rfull = neg ? uint32_t(uint16_t(0u - uint16_t(bf))) : bf;
            if (byte) rfull = (bf & 0xFF00u) | (r & 0xFFu);
            fm = 0;
            break;
        }
        case kAdjd:
        case kAdja:
            // A bare ADJD/ADJA row only ARMS the adjust; its own SIGMA is a
            // pass-through and is never consumed in the ROM.
            r = b;
            rfull = bf;
            fm = 0;
            break;
        case kPass:
        default:
            r = b;
            rfull = bf;
            // MEASURED: PASS drives the full arithmetic set with CY/AC/V = 0
            // (AAM's final `SIGMA -> AL W` and signed DIV's quotient write --
            // docs/facts/undefined_flags.md).
            fm = kArithMask;
            f |= szp(r, byte);
            break;
    }

    res.value = uint16_t(rfull & 0xFFFFu);
    res.flags = f;
    res.flag_mask = fm;
    return res;
}

AluResult alu_step(Machine& m, const AluLatch& lat) {
    AluResult res;
    uint8_t op = lat.op;
    if (op == kOpc) op = alu_opc_select(m);

    bool byte = lat.byte;
    int w = byte ? 8 : 16;
    uint32_t mask = byte ? 0xFFu : 0xFFFFu;
    uint32_t msb = byte ? 0x80u : 0x8000u;
    uint32_t a = m.tmpb & mask;
    uint16_t hi_keep = uint16_t(m.tmpb & ~mask);
    uint32_t cin = (m.psw & kFlagCY) ? 1u : 0u;
    uint16_t f = 0;
    uint32_t r = 0;
    bool cy = false;

    switch (op) {
        case kRol:
            cy = (a & msb) != 0;
            r = ((a << 1) | (cy ? 1u : 0u)) & mask;
            break;
        case kRor:
            cy = (a & 1u) != 0;
            r = ((a >> 1) | (cy ? msb : 0u)) & mask;
            break;
        case kRcl:
            cy = (a & msb) != 0;
            r = ((a << 1) | cin) & mask;
            break;
        case kRcr:
            cy = (a & 1u) != 0;
            r = ((a >> 1) | (cin ? msb : 0u)) & mask;
            break;
        case 0x0E:  // [-0E-]: the second SHL encoding (group /6, "shl6")
        case kShl:
            cy = (a & msb) != 0;
            r = (a << 1) & mask;
            break;
        case kShr:
            cy = (a & 1u) != 0;
            r = (a >> 1) & mask;
            break;
        case kSar:
            cy = (a & 1u) != 0;
            r = ((a >> 1) | (a & msb)) & mask;
            break;
        case kMul: {
            // Shift-add step.  tmpa is the multiplier/low-product register;
            // tmpb the running high half; port B (tmpc) the multiplicand.
            const uint16_t tmps[4] = {m.tmpa, m.tmpb, m.tmpc, 0};
            uint32_t mplier = m.tmpa & mask;
            uint32_t mcand = tmps[lat.tmp & 3] & mask;
            uint32_t sum = a + ((mplier & 1u) ? mcand : 0u);
            uint32_t cout = (sum >> w) & 1u;
            uint32_t new_hi = ((sum & mask) >> 1) | (cout << (w - 1));
            uint32_t new_lo = ((mplier >> 1) | ((sum & 1u) << (w - 1))) & mask;
            m.tmpa = uint16_t((m.tmpa & ~mask) | new_lo);
            r = new_hi;
            res.value = uint16_t(hi_keep | uint16_t(r));
            res.flag_mask = 0;
            return res;
        }
        case kDiv: {
            // Restoring division step: shift {tmpb:tmpa} left one, subtract
            // the divisor from the high half when it fits, quotient bit into
            // tmpa's LSB.
            const uint16_t tmps[4] = {m.tmpa, m.tmpb, m.tmpc, 0};
            uint32_t divisor = tmps[lat.tmp & 3] & mask;
            uint32_t lo = m.tmpa & mask;
            uint32_t hi = ((a << 1) | (lo >> (w - 1)));
            lo = (lo << 1) & mask;
            if (hi >= divisor) {
                hi -= divisor;
                lo |= 1u;
            }
            m.tmpa = uint16_t((m.tmpa & ~mask) | (lo & mask));
            r = hi & mask;
            res.value = uint16_t(hi_keep | uint16_t(r));
            res.flag_mask = 0;
            return res;
        }
        case kRol12: {
            // ROL4: rotate the operand left by one BCD digit through AL.
            r = ((a << 4) | ((a >> (w - 4)) & 0xFu)) & mask;
            res.value = uint16_t(hi_keep | uint16_t(r));
            res.flag_mask = 0;
            return res;
        }
        default: {
            // Not an iterative op: a single combinational evaluation.
            AluLatch l = lat;
            return alu_eval(m, l);
        }
    }

    // shift / rotate flag taps
    if (cy) f |= kFlagCY;
    bool left = (op == kRol || op == kRcl || op == kShl || op == 0x0E);
    bool v;
    if (left)
        v = (((r & msb) != 0) != cy);
    else
        v = (((r & msb) != 0) != (((r << 1) & msb) != 0));
    if (v) f |= kFlagV;
    if (op == kShl || op == kShr || op == kSar || op == 0x0E) {
        // MEASURED: AC always 0 for the shifts.
        f |= szp(r, byte);
        res.flag_mask = kArithMask;
    } else {
        res.flag_mask = kFlagCY | kFlagV;  // rotates touch CY and V only
    }
    res.flags = f;
    res.value = uint16_t(hi_keep | uint16_t(r));
    return res;
}

}  // namespace sim
