# SURVEY FIX #1 — `A1` RESULTS, AS REGISTERED

Prereg + errata: `docs/notes/fz2_a1_prereg_2026-08-10.md` (§1-§6 committed at
`709bf3ba9e`, E-1 at `4d4b26a24a`, E-1.2 at `9be7f99a2c`, all **before** the
RTL was touched).

**The landing is `L1`** — the primary form, taken; `L2` was not needed.
**`sim/` is not touched** (the model is defunct by user ruling of this sitting).

---

## 0. A RIG-INTEGRITY FINDING THAT COMES FIRST, BECAUSE IT INVALIDATED A
##    MEASUREMENT AND WOULD HAVE INVALIDATED THE REST

**A CONCURRENT AGENT IS EDITING THE SAME WORKING TREE.**  While this sitting's
first two baselines were being taken, `hdl/rtl/ucore/v30u_biu.sv`,
`hdl/rtl/ucore/v30u_ss_pkg.sv` and `sw/ss_lint.py` carried that agent's
UNCOMMITTED `F58` (the HALT-cycle address, survey fix #2).  `check_seq.tb_bin`
rebuilds on a content key, so **both of those baselines were measured on a
binary built from another agent's work in progress**, and the difference is not
academic: the same instrument reads **`CLEAN 346 / 725`** on the shared tree
and **`CLEAN 334 / 725`** on a clean tree at this sitting's own commit — 12
seeds of another landing.

**DISPOSITION.**  Both shared-tree baselines are **DISCARDED**.  This sitting's
own RTL edit was **backed out of the shared tree** (the other agent's hunks left
exactly as found, verified line for line) and every number below was taken in an
**isolated `git worktree` at `9be7f99a2c`**
(`~/.cache/ucsimt-tmp/a1-wt`, detached), with the campaign capture
directories symlinked in because they are `.gitignore`d.  Nothing in §1-§4 was
measured on a tree containing another agent's work.

---

## 1. THE LANDING

`hdl/rtl/ucore/v30u_biu.sv`, and nothing else in the RTL:

* `wire flush_src_live = flush_int_live || flush_nmi;`
* in `qs_e_now`'s REP-withdrawal suppression, the STAGED arm's
  `&& !flush_staged_eval` becomes `&& !flush_src_live`.

`flush_staged_eval` is **kept**: the prereg's §3 said it would be deleted as
subsumed, and that was **wrong in one place** — it has a SECOND consumer, the
idle clock's arbitration point in step (c), which is not a display at all.
Deleting it would have changed arbitration.  **The landing is therefore
strictly smaller than registered: one term swapped in one expression, one wire
added, display-only by construction.**  No flop, no save-state address, no EU
output, no opcode named.

DUT receipts (isolated worktree): BEFORE `7f8ac873fe81fbb3…`,
AFTER `a41741a6b7de57fc…`.

---

## 2. THE RESCORE — **P-1a MISSED: 6 OF THE 19 REGISTERED SEATS CLOSED**

`sw/fz2_a1_rescore.py`, 725 retained captures, 0 errors, 0 `GEN_DRIFT`, both
legs on the isolated worktree.

    row-clean   BEFORE 334 / 725     AFTER 340 / 725
    GAINED (row-clean)                    6
    LOST                                  0
    first divergences moved EARLIER       0
    first divergences moved LATER        13
    seeds whose bad-row count DECREASED  20   (none increased)

**THE SIX THAT CLOSED** — `fz2c/407027`, `fz2c/410078`, `fz2c/411050`,
`fz2e/520052`, `fz2e/521030`, `fz2e/523057`.  All six are `A1`.

**THE TWELVE THAT MOVED BUT DID NOT CLOSE** — `fz2c/407065`, `fz2c/408000`,
`fz2c/409066`, `fz2c/410073`, `fz2e/518024`, `fz2e/518065`, `fz2e/518068`,
`fz2e/519027`, `fz2e/523045`, `fz2e/523046`, `fz2e/526025`, `fz2e/528076` —
**each lost exactly one bad row and each moved its first divergence exactly
`+1`, onto the row after the `E`.**

**THE NINETEENTH SEAT DID NOT MOVE AT ALL, AND ITS REGISTRATION WAS MY OWN
ERROR.**  `fz2e/518009` is `bad` 8 → 8, `first_bad` 3326 unmoved.  **It was
never a predicate carrier**: the rails table this sitting measured and printed
into the prereg shows `q_flush = 0` at its own `E` row (and `flush_rep`,
`flush_stage`, `flush_pend` all 0), so the mechanism §2 of the prereg describes
is not present on it.  §2 said *"20 of the 23"* and E-1.2 listed 19 seats; the
correct carrier count is **19 of the 23** (the 23 minus `fz2e/509036`,
`fz2e/513055`, `fz2e/515042` **and `fz2e/518009`**), of which `fz2e/521075` is
P-1b's registered non-closer, leaving **18 seats that could close**.  **This is
an erratum against my own registration, stated rather than quietly corrected**:
P-1a is scored as registered — **6 of 19** — and the arithmetic that should have
been registered is 6 of 18, with the nineteenth a seed that carries the family's
SIGNATURE but not its MECHANISM.  What `518009` actually is remains open.

**WHY, AND IT IS A MECHANISM, NOT AN EXCUSE.**  The prereg's §1 already
measured the split and named it: on **8 of the 23** the `+1` is ABSORBED by a
bus cycle that was already running, and on **15** the WHOLE entry moves with the
announcement — the vector read, the pushes and the restart fetch are all `+1`
(prereg §1, "a second correction").  This landing is display-only, so it closes
exactly the absorbed class and no more: **6 of the 8 absorbed seeds went clean,
the 7th (`fz2e/521075`) is P-1b's registered non-closer and the 8th
(`fz2e/515042`) is out of scope.**  On the other 12 carriers the display is now
right and **a SECOND, downstream mechanism is what remains**: after a REP
withdrawal that is not bus-limited, the ucore's restart — the redirected fetch
and everything behind it — is still one clock late.  It was invisible while the
display hid it, and it is now the first divergence on 12 `A1` seeds plus
`fz2c/407036`, with a clean one-row signature on every one.  **That is the next
work item and it is NOT claimed here.**

**P-1b MET** — `fz2e/521075`: `bad` 6 → 4 (registered: drops by exactly 2),
`first_bad` 2213 unmoved (registered: does not decrease).

**P-3 MISSED, DIRECTIONALLY MET** — `fz2c/407036` (family `D3`): `bad` 6 → 4,
`first_bad` 3046 → 3048.  Registered as "goes row-clean"; it did not.  It is the
same shape as the 13.

**P-2 HELD** — `fz2e/509036`, `fz2e/513055`, `fz2e/515042` were declared out of
scope in advance and are not counted; none of them moved.

**P-4 MET — ZERO LOST.**  Over all 725: no seed's `first_bad` decreased and no
row-clean seed became dirty.  **Every one of the 20 seeds that moved moved in
the same direction.**

### 2.1 THE SAME DELTA, RE-MEASURED ON THE MERGED TREE — F58 AND THIS LANDING ARE INDEPENDENT

While this sitting ran, the concurrent agent COMMITTED `F58` (`b245334d7c`),
so the landing goes on top of it rather than beside it.  The rescore was
therefore re-run on the merged tree, **against a BEFORE leg that is `F58`
alone** (the shared-tree measurement of §0, which is the wrong control for this
landing in isolation and the RIGHT one for the merged tree):

    clean            346 / 725   ->   352 / 725
    GAINED            6   -- `fz2c/407027` `fz2c/410078` `fz2c/411050`
                             `fz2e/520052` `fz2e/521030` `fz2e/523057`
    LOST              0
    moved EARLIER     0
    moved LATER      13

**The same six seeds, the same zero, the same thirteen.**  The two landings do
not interact on this corpus.  Merged-tree DUT receipt `320134a7b961ba36…`.

---

## 3. THE STANDING GATES

| gate | registered | measured | verdict |
|---|---|---|---|
| `gen_ucore_qsf.py --check` | up to date | up to date | **MET** |
| `r7_lint.py` | PASS, 0 undeclared carriers | PASS, 0 / 0 / 0 | **MET** |
| build + receipt | receipted | `a41741a6b7de57fc…` | **MET** |
| `ss_lint.py` (P-5) | UNMOVED | `101×2 BIU + 122×2 EU + tag = 224`, BIU 83 flops, EU 129 (127 mapped + 2 whitelisted), census **212** — **identical to the same command run on the same worktree with the change stashed** | **MET** |
| `test_artifact.py` | 45/45 | 45/45 | **MET** |
| `check_core.py --opcodes all --cases 0` (P-7) | 169,000 / 169,000 | **169,000 / 169,000** full, cycles AND arch, 348 forms — including **`INT.F3AA` 200/200**, `INT.FB` 200/200, `NMI.90` 200/200, `NMI.B8` 200/200 | **MET** |
| the four HLT sweeps (P-8) | 279 / 283 | **97 · 93 · 45 · 44 = 279 / 283** | **MET** |
| `ulockstep.py --golden all --cases 50` (P-13) | informational | **17,350 / 17,350 LOCKSTEP** | informational, unmoved |
| `wrfuzz_wr1_guard.py` (P-9) | 4 clauses green | **NOT RUNNABLE ON THIS BRANCH** — see §3.1 | **NOT RUN** |
| `timed_fuzz --core ucore --seeddir …/b2-tranche/seeds` (P-10) | ≥ 182 / 188 | **NOT RUNNABLE ON THIS BRANCH** — see §3.1 | **NOT RUN** |
| `quartus_gate.py` × 2 (P-12) | ≈ 40 MHz band, TNS 0.000 | see §4 | see §4 |

**`INT.F3AA` at 200/200 is the gate that decided `L1` vs `L2`.**  It is the
35-withdrawal maskable population `flush_int_live` was measured on, and it is
the cell the prereg registered as the one that would refute `L1`.  It did not
fire, so `L1` stands and `L2` was not taken.

### 3.1 TWO REGISTERED GATES ARE NOT RUNNABLE ON THIS BRANCH, AND THE CAUSE IS NOT THIS LANDING

Both fail as **`GEN_DRIFT` on every seed** — the image a v1-era seed regenerates
to no longer matches the one it was banked with, because fuzz-v2 plan **D9**
made the `0F` scrub unconditional in `sw/fuzz_campaign.py`.  `standing_gates.md`
already records exactly this for the four v1 fuzz banks ("**the v1 corpus
stopped being replayable on this branch when D9 landed**"); the `wr1` guard and
the `b2` tranche are in the same condition and the quick reference does not yet
say so.

* `wr1` guard: `w32_launch` returns `ENGINE_ERROR / GEN_DRIFT` on 380 of 380
  retained captures, so both legs score `0 / 0` and three of the four clauses
  read FAIL vacuously.  ⚠ It also needed `sw/testdata/campaigns/wr1/captures`,
  which is `.gitignore`d and therefore absent from any worktree.
* `b2` tranche: `GEN_DRIFT = 216`, `SCORED 0`.
* **CONTROL, so this is not an artefact of the worktree**: the identical
  `GEN_DRIFT` is reproduced in the MAIN checkout, which does **not** contain
  this landing.

**Consequence, stated plainly**: this landing's zero-loss evidence is the fz2
rescore (725 captures, 0 lost, 0 moved earlier), `check_core`'s 169,000 silicon
goldens and the HLT sweeps.  **It has NOT been scored against the `wr1` or
`b2` corpora and no claim is made about them.**

---

## 4. G6

All draws in the isolated worktree, CONTROL/DEFAULT configuration (no
`X1_AD_RETENTION`), `db`/`incremental_db`/`output_files_ucore` deleted first —
`quartus_gate.py`'s own behaviour, so these are clean compiles, not incremental
ones.

| draw | verdict | Fmax (`divclk`) | worst setup | TNS setup/hold | ALMs | errors / latches / `lpm_divide` | receipt |
|---|---|---|---|---|---|---|---|
| 1, WITH the change | **PASS** | **39.81 MHz** | **+6.132 ns** | **0.000 / 0.000, every domain** | 12,243 / 41,910 (29 %) | 0 / 0 / 0 | `cdd8a38816beb671…` |
| 2, WITH the change | **PASS** | **39.81 MHz** | **+6.132 ns** | **0.000 / 0.000, every domain** | 12,243 / 41,910 (29 %) | 0 / 0 / 0 | `51c616317b8b4941…` |
| CONTROL, same commit WITHOUT the change | *(below)* | | | | | | |

Both draws are clean compiles from a deleted `db`, 655 s and 595 s, and they
agree to the digit on all four bars.

**⚠ READ THIS BEFORE QUOTING 39.81.**  It clears the registered bar (≥ 32 MHz,
worst setup > 0, TNS 0.000 both ways) and it is BELOW the 45-48 MHz band the
quick reference records for this tree — but **that band was measured on a
different tree**: this branch has taken several landings since, and the ALM
count has moved 11,147 → 12,243 (+1,096) which one 2-input OR cannot explain.
`standing_gates.md` §A's rule applies in full — **one green build is not
closure, and the same tree has drawn 19.42 and 45.91 MHz.**  The CONTROL draw
in the third row is what separates "this branch" from "this landing"; it is the
only row that can, and no attribution may be made without it.

---

## 5. WHAT THIS SITTING ESTABLISHES, AND WHAT IT DOES NOT

**ESTABLISHES.**  The `EMPTY` announcement of a REP withdrawal is one clock late
in the ucore whenever the recognition standing at the withdrawal is the
NON-MASKABLE one, because the staged arm was given the maskable pin and only the
maskable pin.  Over the 356 retained event-free captures the display is held by
that arm and by nothing else on 13 clean-prefix rows, all 13 with the NMI latch
standing, and **silicon shows `EMPTY` on that very row on 13 of 13**.  With one
term swapped the ucore matches silicon on that row and **6 seeds go row-clean
with 0 lost**.

**DOES NOT ESTABLISH.**  That family `A1` is closed — it is not.  **13 of its
seeds now fail one row later**, on a second and different mechanism: the restart
after a non-bus-limited REP withdrawal is still one clock late.  Nor does it say
anything about the three `stim` seeds, which no offline instrument in this tree
can reach, or about the `wr1`/`b2` corpora, which this branch cannot replay.
